### ISSUE TITLE
Refact: server/modules folder to es6

### ISSUE THREAD

**Issue by QuentinVecchio** [hbogaeus/chicago-brick#12]
This involves the following files:

- [x] client_control_state_machine.js #46 
- [x] layout_state_machine.js #45 
- [x] layout.js Already in ES6
- [x] module.js Already in ES6
- [x] module_def.js #44 
- [x] module_library.js #43 
- [x] module_loader.js #42 
- [x] module_state_machine.js #41 
- [x] module_ticker.js #38 
- [x] playlist_driver.js #37 
- [x] playlist_loader.js #39 
- [x] server_state_machine.js #40

**Comment by oskarcasselryd** [comment]
It seems like most of these already follow es6 standards. Someone with more js experience could have a look and see if something can be improved anyway.
