### ISSUE TITLE
Refact: client/modules folder to es6

### ISSUE THREAD

**Issue by guipingxie1** [hbogaeus/chicago-brick#5]
This involves the following files:

- [x] client_state_machine.js #22 
- [x] module_manager.js #23 
- [x] module_ticker.js #24 
- [x] module.js #25
